- name: create grafana conf path
  file:
    path: "{{ monitoring_project_path }}/grafana"
    state: directory

- name: copy grafana provisioning files
  synchronize:
    src: ./grafana/provisioning/
    dest : "{{ monitoring_project_path }}/grafana/provisioning/"
    delete: yes
    recursive: yes
  notify: restart grafana

- name: copy grafana dashboards
  synchronize:
    src: ./grafana/dashboards/
    dest : "{{ monitoring_project_path }}/grafana/dashboards/"
    delete: yes
    recursive: yes
  notify: restart grafana

- name: create grafana data path
  file:
    path: "{{ grafana_data_path }}"
    state: directory
    owner: 472
    group: 472
  become: yes
