monitoring_project_path: ~/monitoring
monitoring_ec2_name_prefix: aboutops.io-
monitoring_username: admin
monitoring_password: 9S2cP86D5Iyu

grafana_data_path: /data/grafana
grafana_domain: localhost

prometheus_data_path: /data/prometheus
prometheus_domain: localhost

alertmanager_domain: localhost

api_domain: localhost
admin_domain: localhost

cloudwatchexporter_regions:
  - ap-southeast-1

