vpc_cidr = "10.1.0.0/16"
s3_bucket_name = "globalinside"
web_1_instances_type = "t3.small"
web_2_instances_type = "t3.small"
mairadb_1_instances_type = "t3.medium"
mariadb_2_instances_type = "t3.medium"
storage_instances_type = "t3.small"
