{
 "title": "Prometheus",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(node_boot_time_seconds, project)"
   }
  ]
 },
 "panels": [
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(avg by (instance, mountpoint) (node_filesystem_avail_bytes{mountpoint=~\"/|/data\", project=\"$project\"}))\n/\n(avg by (instance, mountpoint) (node_filesystem_size_bytes{mountpoint=~\"/|/data\", project=\"$project\"}))",
     "legendFormat": "{{instance}} [ {{mountpoint}} ]"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-node_memory_MemAvailable_bytes{project=\"$project\"}/node_memory_MemTotal_bytes{project=\"$project\"}",
     "legendFormat": "{{instance}} {{B}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\", project=\"$project\"}[5m])))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}